policies:
  - id: find_peak_policy
    policy_cls: SingleStageChainingPolicy
    condition_cls: ChainingPeakCondition
    condition_kwargs:
      key: peaks
    next_stage_ids:
      - process_peak

  - id: process_peak_policy
    policy_cls: SingleStageChainingPolicy
    condition_cls: TrueCondition
    next_stage_ids:
      - find_peaks # Example of requesting a previous stage

stages:
  - id: cut
    stage_cls: CutStage
    kwargs:
      cut_point: 200

  - id: filter
    stage_cls: FilterStage

  - id: background
    stage_cls: BackgroundStage

  - id: find_peaks
    stage_cls: FindAllPeaksStage
    policy_id: find_peak_policy

  - id: process_peak
    stage_cls: ProcessFitPeakStage
    policy_id: process_peak_policy

execution_order:
  - cut
  - filter
  - background
  - find_peaks
