"""
stage_request.py.

This module defines data structures representing requests to add
new stages to the SAXS (Small-Angle X-ray Scattering) processing
pipeline.

These requests are generated by stages during execution and are
handled by the scheduler. They carry metadata describing both the
current stage evaluation context and the parameters required to
insert and execute new stages in the pipeline.

Classes
-------
AbstractStageRequest
    Abstract base class representing a generic stage addition
    request in the pipeline.

StageRequest
    Concrete implementation carrying specific stage and scheduler
    metadata for insertion decisions.
"""

from dataclasses import dataclass

from saxs.saxs.core.types.scheduler_objects import AbstractSchedulerMetadata
from saxs.saxs.core.types.stage_objects import AbstractStageMetadata


@dataclass(frozen=True)
class AbstractStageRequest:
    """
    Base class for stage addition requests.

    Defines the minimal interface for requests generated by stages
    to suggest new stage insertions into the pipeline. The scheduler
    determines whether and where these requested stages are added,
    depending on its insertion policy and current execution context.

    Notes
    -----
    Subclasses should include metadata describing the context in
    which the request was made and the data relevant for evaluating
    insertion conditions.
    """


@dataclass(frozen=True)
class StageRequest(AbstractStageRequest):
    """
    Concrete request for adding a new stage to the pipeline.

    Encapsulates both stage-level and scheduler-level metadata
    necessary for the scheduler to decide whether to insert the
    requested stage and how to configure it.

    Attributes
    ----------
    eval_metadata : AbstractStageMetadata
        Metadata describing the evaluation context of the stage
        that generated this request.
    pass_metadata : AbstractStageMetadata
        Metadata passed forward to the next stage for contextual
        processing.
    scheduler_metadata : AbstractSchedulerMetadata
        Metadata containing scheduler-level information, such as
        iteration counts or peak indices, relevant for insertion
        policies.
    """

    eval_metadata: AbstractStageMetadata
    pass_metadata: AbstractStageMetadata
    scheduler_metadata: AbstractSchedulerMetadata
