"""
stage_request.py.

This module defines data structures representing requests to add
new stages to the SAXS (Small-Angle X-ray Scattering) processing
pipeline.

These requests are generated by stages during execution and are
handled by the scheduler. They carry metadata describing both the
current stage evaluation context and the parameters required to
insert and execute new stages in the pipeline.

Classes
-------
IAbstractStageRequest
    Abstract base class representing a generic stage addition
    request in the pipeline.

StageRequest
    Concrete implementation carrying specific stage and scheduler
    metadata for insertion decisions.
"""

from dataclasses import dataclass

from saxs.core.types.flow_metadata import FlowMetadata


@dataclass(frozen=False)
class IAbstractStageRequest:
    """
    Base class for stage addition requests.

    Defines the minimal interface for requests generated by stages
    to suggest new stage insertions into the pipeline. The scheduler
    determines whether and where these requested stages are added,
    depending on its insertion policy and current execution context.

    Notes
    -----
    Subclasses should include metadata describing the context in
    which the request was made and the data relevant for evaluating
    insertion conditions.
    """


class EvalMetadata(FlowMetadata):
    """Eval metadata.

    It is a child of Flow meta because we pass from flow metadata.
    """

    Keys = FlowMetadata.Keys
    Dict = FlowMetadata.Dict


@dataclass(frozen=False)
class StageRequest(IAbstractStageRequest):
    """
    Concrete request for adding a new stage to the pipeline.

    Encapsulates both stage-level and scheduler-level metadata
    necessary for the scheduler to decide whether to insert the
    requested stage and how to configure it.

    Attributes
    ----------
    condition_eval_metadata : AbstractStageMetadata
        Metadata describing the evaluation context of the stage
        that generated this request.
    flow_metadata : FlowMetadata
        Metadata passed forward to the next stage for contextual
        processing.
    """

    condition_eval_metadata: EvalMetadata
    flow_metadata: FlowMetadata
